### PR TITLE
Can anyone help me with my software 

### PR DESCRIPTION
**Pull request by escorosecurityconsultants**
I am having issue with my software If someone can email me on mohammed@escrowsecurityconsultants.co.uk 

I will appreciate you help and support. Thanks

### CODE REVIEW

**Comment by dusanmsk** [comment]
> I am having issue with my software If someone can email me on [mohammed@escrowsecurityconsultants.co.uk](mailto:mohammed@escrowsecurityconsultants.co.uk)

Possibly nobody will help you with your software, especially when you ask for a support by creating pull request (WTF?). If you have any problems with railduino, ask in forum or open a issue. This PR will be rejected.

**Comment by Rubeast** [comment]
Lol. Professional security consultant is not very professional..

**Comment by escorosecurityconsultants** [comment]
First of all my business doesn’t involve in dealing with coding security or software security.
The reason why I asked for your help was to see that the Chinese vendor I purchased my software from is now extorting me for more money and hence he’s even locked my own access and therefore I needed your help to check what exactly has happened.


I didn’t realise that I was going to get judged for lack of knowledge in coding!

Thanks

Mohammed


Director of Escrow Security Consultants





Mobile: +44 7572 824 284







CONFIDENTIALITY NOTICE -- This email is intended only for the person(s) named in the message header. Unless otherwise indicated, it contains information that is confidential, privileged and/or exempt from disclosure under applicable law. If you have received this message in error, please notify the sender of the error and delete the message. Thank you. This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Comment by escorosecurityconsultants** [comment]
Hi

First of all my business doesn’t involve in dealing with coding security or software security. therefore I don’t know how to contact individuals to seek help or support. Hence why I thought writing a comment might able you to contact me.

The reason why I asked for your help was to see that the Chinese vendor I purchased my software from is now extorting me for more money and hence he’s even locked my own access and therefore I needed your help to check what exactly has happened.

I didn’t realise that I was going to get judged for lack of knowledge in coding!

Thanks


Mohammed


Director of Escrow Security Consultants





Mobile: +44 7572 824 284







CONFIDENTIALITY NOTICE -- This email is intended only for the person(s) named in the message header. Unless otherwise indicated, it contains information that is confidential, privileged and/or exempt from disclosure under applicable law. If you have received this message in error, please notify the sender of the error and delete the message. Thank you. This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Pull request closed without merging**
